"""The demo export ships in qdaPy and qdaR and must be the same study.

``zotqda-fragments-demo.csv`` and ``zotqda-history-demo.csv`` are a genuine
zotQDA export, generated by the plugin's own export code via
``tools/gen-demo-study.js`` in the zotQDA repository.  These tests freeze the
study's shape and its headline coefficients, and hold the two shipped copies
to byte identity -- the same discipline the frozen qdaZ references follow.

The fragments file is zotQDA's *last-state* export: one row per annotation and
code, a single ``codedBy`` per row.  Intercoder agreement between two coders on
one segment collapses there and cannot be recovered, so reliability is computed
from the *history* -- the coding log, one row per event -- via
:func:`qdapy.codings`, exactly as qdaZ computes it.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import qdapy


def test_demo_fragments_shape():
    frag = qdapy.read_fragments(qdapy.example("zotqda-fragments-demo.csv"))
    # last-state export: one row per (annotation, code); read the actual count
    assert len(frag) > 0
    assert frag["code"].nunique() == 9
    assert frag["citekey"].nunique() == 8
    assert sorted(frag["codedBy"].unique()) == ["ann", "bob"]
    assert (frag["positionKind"] == "text").all()


def test_demo_agreement_frozen():
    # per-coder truth lives only in the history; reconstruct it, then compare
    hist = qdapy.read_history(qdapy.example("zotqda-history-demo.csv"))
    matrix = qdapy.units(qdapy.codings(hist), coder="user")
    a = qdapy.agreement.agreement(matrix)
    assert float(a["alpha"].iloc[0]) == pytest.approx(0.6716, abs=1e-4)
    assert float(a["ac1"].iloc[0]) == pytest.approx(0.6740, abs=1e-4)
    assert int(a["multi_set_aside"].iloc[0]) > 0


def test_demo_agreement_level_effect():
    # a hierarchical scheme reads more reliably nearer the root: coders who
    # split over leaves still agree on the theme
    hist = qdapy.read_history(qdapy.example("zotqda-history-demo.csv"))
    codings = qdapy.codings(hist)
    leaf = qdapy.agreement.agreement(qdapy.units(codings, coder="user"))
    theme = qdapy.agreement.agreement(
        qdapy.units(codings, coder="user", level=1)
    )
    assert float(theme["alpha"].iloc[0]) == pytest.approx(0.8965, abs=1e-4)
    assert float(theme["ac1"].iloc[0]) == pytest.approx(0.8984, abs=1e-4)
    assert float(theme["alpha"].iloc[0]) > float(leaf["alpha"].iloc[0])


def test_demo_history_reads():
    hist = qdapy.read_history(qdapy.example("zotqda-history-demo.csv"))
    assert set(hist["action"]) == {"add", "remove"}
    assert (hist["action"] == "remove").sum() == 6


@pytest.mark.parametrize("name", ["zotqda-fragments-demo.csv",
                                  "zotqda-history-demo.csv"])
def test_demo_identical_in_qdar(name):
    theirs = Path(__file__).parents[2] / "qdaR" / "inst" / "extdata" / name
    if not theirs.exists():
        pytest.skip("qdaR sources not present")
    ours = Path(qdapy.example(name))
    assert ours.read_bytes() == theirs.read_bytes()
