"""Reading a REFI-QDA project, and being honest about what it cannot give.

The fixture is generated by scripts/make_qdpx_fixture.py and shipped with the
package, so these tests need neither Zotero nor MAXQDA.
"""

from __future__ import annotations

import zipfile
from pathlib import Path

import pandas as pd
import pytest

import qdapy

FIXTURE = Path(str(qdapy.example("sample.qdpx")))


@pytest.fixture
def project() -> qdapy.QdpxProject:
    return qdapy.read_qdpx(FIXTURE, warn=False)


# ------------------------------------------------------------- the reading --


def test_fixture_ships_with_the_package() -> None:
    assert FIXTURE.exists()
    assert "sample.qdpx" in qdapy.example()


def test_codings_and_codebook(project: qdapy.QdpxProject) -> None:
    assert len(project.fragments) == 7
    assert len(project.codebook) == 4
    assert project.coders == ["Ann", "Bob"]
    assert project.sources == ["Interview 01", "Interview 02", "Leitfaden"]


def test_code_paths_are_nested(project: qdapy.QdpxProject) -> None:
    paths = set(project.codebook["code"])
    assert paths == {
        "Belastung", "Belastung/beruflich", "Belastung/privat", "Ressourcen",
    }
    child = project.codebook.set_index("code").loc["Belastung/beruflich"]
    assert child["parent"] == "Belastung"
    assert child["level"] == 2
    # colour is inherited where the child does not set its own
    assert child["color"] == "#CC3311"


def test_code_identity_is_the_refi_guid(project: qdapy.QdpxProject) -> None:
    """codeId has to survive a rename, and REFI's GUID is exactly that."""
    ids = project.codebook.set_index("code")["codeId"]
    assert ids["Belastung"] == "AAAAAAA1-0000-0000-0000-000000000001"
    assert project.fragments["codeId"].isin(set(ids)).all()


def test_text_comes_from_an_internal_file(project: qdapy.QdpxProject) -> None:
    row = project.fragments.set_index("annotationKey").loc[
        "CCCCCCC1-0000-0000-0000-000000000001"
    ]
    assert row["text"].iloc[0].startswith("Die Arbeit war fordernd")


def test_text_comes_from_inline_content(project: qdapy.QdpxProject) -> None:
    """Some tools write plainTextPath, others PlainTextContent. Both must work."""
    rows = project.fragments[project.fragments["title"] == "Interview 02"]
    assert rows["text"].iloc[0].startswith("Am Anfang habe ich")


def test_positions_survive(project: qdapy.QdpxProject) -> None:
    text = project.fragments[project.fragments["positionKind"] == "text"]
    assert (text["positionStart"] != "").all()
    assert (text["positionEnd"] != "").all()


def test_pdf_selection_keeps_page_and_rectangle(project: qdapy.QdpxProject) -> None:
    pdf = project.fragments[project.fragments["positionKind"] == "pdf"]
    assert len(pdf) == 1
    assert pdf["positionPage"].iloc[0] == 2  # numeric, like the CSV reader
    assert pdf["positionRects"].iloc[0] == "72 640 480 700"


def test_coders_and_timestamps(project: qdapy.QdpxProject) -> None:
    assert set(project.fragments["codedBy"]) == {"Ann", "Bob"}
    assert (project.fragments["codedAt"] != "").all()


def test_a_selection_without_coding_becomes_uncoded(
    project: qdapy.QdpxProject,
) -> None:
    assert len(project.uncoded) == 1
    assert project.uncoded["code"].iloc[0] == ""
    assert project.uncoded["zotqdaFormat"].iloc[0] == "uncoded/1"


def test_multiple_coding_is_found(project: qdapy.QdpxProject) -> None:
    assert len(project.multi_coded) == 1
    row = project.multi_coded.iloc[0]
    assert row["coder"] == "Ann"
    assert row["n"] == 2
    assert row["codes"] == "Belastung/beruflich+Belastung/privat"


def test_history_holds_additions_only(project: qdapy.QdpxProject) -> None:
    assert set(project.history["action"]) == {"add"}
    assert project.history["ts"].is_monotonic_increasing


# ------------------------------------------------- what it refuses to hide --


def test_unsupported_elements_are_counted_not_dropped(
    project: qdapy.QdpxProject,
) -> None:
    """A project half of which is audio must not look like a whole one."""
    assert project.skipped == {"PictureSource": 1, "Cases": 1, "Notes": 1}


def test_the_import_warns_by_default() -> None:
    with pytest.warns(UserWarning, match="subset of the analyses"):
        qdapy.read_qdpx(FIXTURE)


def test_limitations_name_the_missing_pieces(project: qdapy.QdpxProject) -> None:
    joined = " ".join(project.limitations)
    for expected in ("citekey", "consensus", "abbreviation", "additions only"):
        assert expected in joined


def test_limitations_are_specific_to_the_file(tmp_path: Path) -> None:
    """Strip the coders out and the warning has to say so, not stay generic."""
    stripped = tmp_path / "no-users.qdpx"
    with zipfile.ZipFile(FIXTURE) as src, zipfile.ZipFile(stripped, "w") as out:
        for name in src.namelist():
            blob = src.read(name)
            if name == "project.qde":
                blob = blob.replace(b'creatingUser="11111111', b'x="11111111')
                blob = blob.replace(b'creatingUser="22222222', b'x="22222222')
            out.writestr(name, blob)
    project = qdapy.read_qdpx(stripped, warn=False)
    assert any("no coders recorded" in x for x in project.limitations)


def test_a_zip_without_project_qde_is_refused(tmp_path: Path) -> None:
    bad = tmp_path / "not-a-project.qdpx"
    with zipfile.ZipFile(bad, "w") as zf:
        zf.writestr("readme.txt", "nothing to see")
    with pytest.raises(ValueError, match=r"no project\.qde"):
        qdapy.read_qdpx(bad, warn=False)


def test_frames_say_where_they_came_from(project: qdapy.QdpxProject) -> None:
    """Downstream code, and the reader of a script, must be able to tell."""
    assert project.fragments.attrs["qda_origin"] == "qdpx"
    assert project.fragments.attrs["qda_format"] == "fragments"


# ------------------------------------------- the analyses actually run on it --


def test_counts_and_matrix(project: qdapy.QdpxProject) -> None:
    counts = qdapy.code_counts(project.fragments)
    assert counts.set_index("code")["n"]["Ressourcen"] == 2
    assert not qdapy.code_matrix(project.fragments, long=False).empty


def test_agreement_runs_and_sets_the_multiple_coding_aside(
    project: qdapy.QdpxProject,
) -> None:
    u = qdapy.units(project.fragments)
    res = qdapy.agreement.agreement(u)
    assert int(res["multi_set_aside"].iloc[0]) == 1
    assert 0.0 <= float(res["percent"].iloc[0]) <= 1.0
    assert int(res["coders"].iloc[0]) == 2


def test_unitizing_runs_because_positions_survived(
    project: qdapy.QdpxProject,
) -> None:
    segments = qdapy.segments(project.fragments)
    assert set(segments) == {"Ann", "Bob"}
    result = qdapy.unitizing_alpha(list(segments.values()))
    assert result["Do"] > 0


def test_saturation_runs_off_the_reconstructed_log(
    project: qdapy.QdpxProject,
) -> None:
    sat = qdapy.saturation(project.history)
    assert sat["codes"].is_monotonic_increasing
    assert sat["codes"].iloc[-1] == 4


def test_consensus_analyses_have_nothing_to_read(
    project: qdapy.QdpxProject,
) -> None:
    """The point of the limitation list: this is not an oversight."""
    assert not hasattr(project, "consensus_mapping")
    assert any("consensus" in x for x in project.limitations)


def test_crosstabs_by_metadata_are_empty_not_wrong(
    project: qdapy.QdpxProject,
) -> None:
    """No bibliographic data is better than invented bibliographic data."""
    for column in ("citekey", "creator", "year"):
        assert (project.fragments[column] == "").all()


def test_a_frame_from_qdpx_is_shaped_like_one_from_csv() -> None:
    """Same columns, so nothing downstream needs to know where it came from."""
    csv = qdapy.read_fragments(qdapy.example("zotqda-fragments.csv"))
    qdpx = qdapy.read_qdpx(FIXTURE, warn=False).fragments
    assert list(csv.columns) == list(qdpx.columns)
    assert isinstance(qdpx, pd.DataFrame)
