#!/usr/bin/env python3
"""Write the language switcher's page-to-page map.

The switcher in the header is a static menu, so out of the box it sends
every reader to the front page of the other language. This walks the two
sidebars in parallel — en/_quarto.yml and de/_quarto.yml list the same
pages in the same order, in two languages — and writes the pairing, the
retargeting logic and the version banner as theme/scripts.html, which
both projects inline into every page (include-after-body is depth-blind,
so a relative <script src> would only work from the site root).

Walking the sidebars rather than keeping a hand-written table means the
map cannot fall behind a page that was added; it means instead that the
two sidebars have to stay parallel, which is checked here and fails the
build if it stops being true.

Needs PyYAML; build.sh runs it with the docs venv, which has it.
"""

import json
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent


def hrefs(node):
    if isinstance(node, list):
        for item in node:
            yield from hrefs(item)
    elif isinstance(node, dict):
        if "href" in node:
            yield node["href"]
        yield from hrefs(node.get("contents", []))


def sidebar(lang):
    cfg = yaml.safe_load((HERE / lang / "_quarto.yml").read_text("utf-8"))
    pages = list(hrefs(cfg["website"]["sidebar"]["contents"]))
    return [p.rsplit(".", 1)[0] + ".html" for p in pages]


def main():
    en, de = sidebar("en"), sidebar("de")
    if len(en) != len(de):
        raise SystemExit(
            f"gen_langmap: the sidebars are no longer parallel "
            f"({len(en)} en pages, {len(de)} de pages) — a page was added "
            "to one language only")
    mapping = {}
    for e, d in zip(en, de):
        mapping[f"en/{e}"] = f"de/{d}"
        mapping[f"de/{d}"] = f"en/{e}"

    langmap = LANGMAP_JS.replace(
        "__MAP__", json.dumps(mapping, indent=2, sort_keys=True,
                              ensure_ascii=False))
    versions = (HERE / "shared" / "versions.js").read_text("utf-8")
    scripts = (f"<script>\n{langmap}</script>\n"
               f"<script>\n{versions}</script>\n")
    for lang in ("en", "de"):
        (HERE / lang / "theme").mkdir(exist_ok=True)
        (HERE / lang / "theme" / "scripts.html").write_text(scripts, "utf-8")
    print(f"wrote en/theme/scripts.html and de/theme/scripts.html "
          f"({len(en)} page pairs)")


LANGMAP_JS = """/* Language switcher: go to the translation of this page, not to the
   front page of the other language. Generated by gen_langmap.py from
   the two sidebars; editing it here would be overwritten on the next
   build. Keys and values are site-root-relative, so the same file works
   over http and from a plain file tree opened with file://. */
(function () {
  var MAP = __MAP__;

  function current() {
    var path = window.location.pathname;
    var m = /\\/(en|de)\\/(.*)$/.exec(path);
    if (!m) return null;
    var rest = m[2] || "index.html";
    if (rest === "" || rest.charAt(rest.length - 1) === "/") {
      rest += "index.html";
    }
    return { lang: m[1], rest: rest, key: m[1] + "/" + rest };
  }

  function retarget() {
    var here = current();
    if (!here) return;
    var target = MAP[here.key];
    if (!target) return;             /* no counterpart: leave the default */
    var up = new Array(here.rest.split("/").length).join("../") + "../";
    var links = document.querySelectorAll(
      'a[href$="/en/index.html"], a[href$="/de/index.html"]');
    for (var i = 0; i < links.length; i++) {
      var href = links[i].getAttribute("href");
      var lang = /\\/(en|de)\\/index\\.html$/.exec(href)[1];
      if (lang === here.lang) {
        /* the entry for the language being read: the page itself */
        links[i].setAttribute("href", up + here.key);
      } else if (target.indexOf(lang + "/") === 0) {
        links[i].setAttribute("href", up + target);
      }
    }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", retarget);
  } else {
    retarget();
  }
})();
"""


if __name__ == "__main__":
    main()
